// Generated by CoffeeScript 1.6.3
var fileName, graph, noflo;

noflo = require("noflo");

fileName = 21;

graph = noflo.graph.createGraph("linecount");

graph.addNode("Read File", "CoreUtil");

graph.addNode("Display", "Output");

graph.addEdge("Read File", "out", "Display", "in");

graph.addInitial(fileName, "Read File", "in");

noflo.createNetwork(graph);
